version: '3'

services:
  offmute-api:
    build: .
    ports:
      - "6543:6543"
    environment:
      - GEMINI_API_KEY=AIzaSyA008hF1g71vaE0JMo7syFWALHP4xRApWU
    volumes:
      - ./uploads:/app/uploads